"""add chat request constraints

Revision ID: 2cb85c38d0e2
Revises: f2220d319037
Create Date: 2026-07-12 12:12:32.543204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cb85c38d0e2"
down_revision: Union[str, Sequence[str], None] = "f2220d319037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_agent_runs_active_root_user",
        "agent_runs",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text(
            "parent_run_id IS NULL AND status IN ('running', 'waiting_for_user')"
        ),
    )
    op.add_column("messages", sa.Column("client_message_id", sa.Uuid(), nullable=True))
    op.create_index(
        "uq_messages_user_client_message_id",
        "messages",
        ["user_id", "client_message_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_messages_user_client_message_id", table_name="messages")
    op.drop_column("messages", "client_message_id")
    op.drop_index(
        "uq_agent_runs_active_root_user",
        table_name="agent_runs",
        postgresql_where=sa.text(
            "parent_run_id IS NULL AND status IN ('running', 'waiting_for_user')"
        ),
    )
    # ### end Alembic commands ###
