"""create conversation summaries

Revision ID: 48e522ae0456
Revises: 2cb85c38d0e2
Create Date: 2026-07-13 00:48:09.207659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48e522ae0456"
down_revision: Union[str, Sequence[str], None] = "2cb85c38d0e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("through_message_id", sa.Uuid(), nullable=False),
        sa.Column("source_summary_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_summary_id"], ["conversation_summaries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["through_message_id"], ["messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversation_summaries_user_id_id",
        "conversation_summaries",
        ["user_id", "id"],
        unique=False,
    )
    op.create_index(
        "uq_conversation_summaries_user_through_message_id",
        "conversation_summaries",
        ["user_id", "through_message_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_conversation_summaries_user_through_message_id",
        table_name="conversation_summaries",
    )
    op.drop_index(
        "ix_conversation_summaries_user_id_id", table_name="conversation_summaries"
    )
    op.drop_table("conversation_summaries")
    # ### end Alembic commands ###
