"""create agent tool calls

Revision ID: 8f4db0f9d565
Revises: 48e522ae0456
Create Date: 2026-07-13 09:16:56.579968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f4db0f9d565"
down_revision: Union[str, Sequence[str], None] = "48e522ae0456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tool_calls",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.String(length=255), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("model_turn_index", sa.Integer(), nullable=False),
        sa.Column("tool_call_index", sa.Integer(), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                "cancelled",
                name="agent_tool_call_status",
            ),
            nullable=False,
        ),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_run_id", "tool_call_id", name="uq_agent_tool_calls_run_tool_call_id"
        ),
    )
    op.create_index(
        op.f("ix_agent_tool_calls_agent_run_id"),
        "agent_tool_calls",
        ["agent_run_id"],
        unique=False,
    )
    op.create_index(
        "uq_agent_tool_calls_run_turn_call",
        "agent_tool_calls",
        ["agent_run_id", "model_turn_index", "tool_call_index"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_agent_tool_calls_run_turn_call", table_name="agent_tool_calls")
    op.drop_index(
        op.f("ix_agent_tool_calls_agent_run_id"), table_name="agent_tool_calls"
    )
    op.drop_table("agent_tool_calls")
    op.execute("DROP TYPE agent_tool_call_status")
    # ### end Alembic commands ###
