"""create messages and agent runs

Revision ID: f2220d319037
Revises: 4b6f1e646712
Create Date: 2026-07-12 08:26:26.210556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f2220d319037"
down_revision: Union[str, Sequence[str], None] = "4b6f1e646712"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", name="message_role"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "generating", "completed", "failed", "cancelled", name="message_status"
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_user_id_id", "messages", ["user_id", "id"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_message_id", sa.Uuid(), nullable=False),
        sa.Column("result_message_id", sa.Uuid(), nullable=True),
        sa.Column("parent_run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "waiting_for_user",
                "completed",
                "failed",
                "cancelled",
                name="agent_run_status",
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_run_id"], ["agent_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["result_message_id"], ["messages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trigger_message_id"], ["messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("result_message_id"),
    )
    op.create_index(
        op.f("ix_agent_runs_parent_run_id"),
        "agent_runs",
        ["parent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_trigger_message_id"),
        "agent_runs",
        ["trigger_message_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_user_id_id", "agent_runs", ["user_id", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_runs_user_id_id", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_trigger_message_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_parent_run_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_messages_user_id_id", table_name="messages")
    op.drop_table("messages")
    op.execute("DROP TYPE agent_run_status")
    op.execute("DROP TYPE message_status")
    op.execute("DROP TYPE message_role")
    # ### end Alembic commands ###
